[package]
org = "xlibb"
name = "asb"
version = "0.1.0"
authors = ["xlibb"]
keywords = ["asb"]
repository = "https://github.com/xlibb/module-asb"
license = ["Apache-2.0"]
distribution = "2201.3.0"
icon = "icon.png"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "asb-native"
version = "0.1.0"
path = "../native/build/libs/asb-native-0.1.0-SNAPSHOT.jar"

# Azure dependencies
[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-messaging-servicebus"
version = "7.13.0"
path = "./lib/azure-messaging-servicebus-7.13.0.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core"
version = "1.34.0"
path = "./lib/azure-core-1.34.0.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core-amqp"
version = "2.8.0"
path = "./lib/azure-core-amqp-2.8.0.jar"

[[platform.java11.dependency]]
groupId = "com.azure"
artifactId = "azure-core-http-netty"
version = "1.12.7"
path = "./lib/azure-core-http-netty-1.12.7.jar"

# Jackson dependencies
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.13.4"
path = "./lib/jackson-annotations-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.13.4"
path = "./lib/jackson-core-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.13.4.2"
path = "./lib/jackson-databind-2.13.4.2.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "2.13.4"
path = "./lib/jackson-datatype-jsr310-2.13.4.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-xml"
version = "2.13.4"
path = "./lib/jackson-dataformat-xml-2.13.4.jar"

# Netty dependencies
[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.82.Final"
path = "./lib/netty-buffer-4.1.82.Final.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.82.Final"
path = "./lib/netty-codec-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-dns"
version = "4.1.82.Final"
path = "./lib/netty-codec-dns-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.82.Final"
path = "./lib/netty-codec-http-4.1.82.Final.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "4.1.82.Final"
path = "./lib/netty-codec-http2-4.1.82.Final.jar"


[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-socks"
version = "4.1.82.Final"
path = "./lib/netty-codec-socks-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.82.Final"
path = "./lib/netty-common-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.82.Final"
path = "./lib/netty-handler-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.1.82.Final"
path = "./lib/netty-handler-proxy-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.82.Final"
path = "./lib/netty-resolver-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns"
version = "4.1.82.Final"
path = "./lib/netty-resolver-dns-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver-dns-classes-macos"
version = "4.1.82.Final"
path = "./lib/netty-resolver-dns-classes-macos-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-dns-native-macos-4.1.82.Final-osx-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.82.Final"
path = "./lib/netty-transport-4.1.82.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-epoll"
version = "4.1.82.Final"
path = "./lib/netty-transport-classes-epoll-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-kqueue"
version = "4.1.82.Final"
path = "./lib/netty-transport-classes-kqueue-4.1.82.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-native-kqueue-4.1.82.Final-osx-x86_64.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.82.Final"
path = "./lib/netty-transport-native-unix-common-4.1.82.Final.jar"

# Netty tcnative dependencies
[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-classes"
version = "2.0.54.Final"
path = "./lib/netty-tcnative-classes-2.0.54.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "2.0.54.Final"
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final-windows-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final-linux-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final-osx-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.54.Final-osx-x86_64.jar"

# Project reactor dependencies
[[platform.java11.dependency]]
groupId = "io.projectreactor"
artifactId = "reactor-core"
version = "3.4.23"
path = "./lib/reactor-core-3.4.23.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-core"
version = "1.0.23"
path = "./lib/reactor-netty-core-1.0.23.jar"

[[platform.java11.dependency]]
groupId = "io.projectreactor.netty"
artifactId = "reactor-netty-http"
version = "1.0.23"
path = "./lib/reactor-netty-http-1.0.23.jar"

# Apache proton-j dependencies
[[platform.java11.dependency]]
groupId = "org.apache.qpid"
artifactId = "proton-j"
version = "0.33.8"
path = "./lib/proton-j-0.33.8.jar"

# Reactive streams dependencies
[[platform.java11.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"
